import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          DEFAULT: "var(--color-primary)",
          hover: "var(--color-primary-600)",
          foreground: "var(--color-text-on-primary)",
        },
        secondary: {
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          DEFAULT: "var(--color-secondary)",
          hover: "var(--color-secondary-600)",
          foreground: "var(--color-text-on-secondary)",
        },
        accent: {
          100: "var(--color-accent-100)",
          200: "var(--color-accent-200)",
          300: "var(--color-accent-300)",
          400: "var(--color-accent-400)",
          500: "var(--color-accent-500)",
          600: "var(--color-accent-600)",
          700: "var(--color-accent-700)",
          800: "var(--color-accent-800)",
          900: "var(--color-accent-900)",
          DEFAULT: "var(--color-accent)",
          hover: "var(--color-accent-600)",
          foreground: "var(--color-text-on-accent)",
        },
        background: "var(--color-background)",
        "background-alt": "var(--color-background-alt)",
        "background-tertiary": "var(--color-background-tertiary)",
        surface: "var(--color-surface)",
        "surface-alt": "var(--color-surface-alt)",
        "surface-elevated": "var(--color-surface-elevated)",
        foreground: "var(--color-text-primary)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-on-primary": "var(--color-text-on-primary)",
        "text-on-secondary": "var(--color-text-on-secondary)",
        "text-on-accent": "var(--color-text-on-accent)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "border-muted": "var(--color-border-muted)",
        muted: "var(--color-muted)",
        "muted-foreground": "var(--color-text-muted)",
        success: {
          DEFAULT: "var(--color-success)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          foreground: "var(--color-success-foreground)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          foreground: "var(--color-warning-foreground)",
        },
        danger: {
          DEFAULT: "var(--color-danger)",
          100: "var(--color-danger-100)",
          200: "var(--color-danger-200)",
          foreground: "var(--color-danger-foreground)",
        },
        error: {
          DEFAULT: "var(--color-danger)",
          hover: "var(--color-danger)",
          foreground: "var(--color-danger-foreground)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          foreground: "var(--color-info-foreground)",
        },
        ring: "var(--color-ring)",
        focus: "var(--color-focus)",
        overlay: "var(--color-overlay)",
        "overlay-strong": "var(--color-overlay-strong)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
        display: ["var(--font-display)"],
      },
      fontSize: {
        "2xs": ["var(--text-2xs)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)" }],
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-relaxed)", letterSpacing: "var(--tracking-normal)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-relaxed)", letterSpacing: "var(--tracking-tight)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-snug)", letterSpacing: "var(--tracking-tight)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--leading-snug)", letterSpacing: "var(--tracking-tight)" }],
        "4xl": ["var(--text-4xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tight)" }],
        "5xl": ["var(--text-5xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "6xl": ["var(--text-6xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
      },
      fontWeight: {
        thin: "var(--font-thin)",
        extralight: "var(--font-extralight)",
        light: "var(--font-light)",
        normal: "var(--font-normal)",
        medium: "var(--font-medium)",
        semibold: "var(--font-semibold)",
        bold: "var(--font-bold)",
        extrabold: "var(--font-extrabold)",
        black: "var(--font-black)",
      },
      lineHeight: {
        none: "var(--leading-none)",
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
        loose: "var(--leading-loose)",
      },
      letterSpacing: {
        tighter: "var(--tracking-tighter)",
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
        wider: "var(--tracking-wider)",
        widest: "var(--tracking-widest)",
      },
      spacing: {
        0: "var(--spacing-0)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
        12: "var(--spacing-12)",
        14: "var(--spacing-14)",
        16: "var(--spacing-16)",
        20: "var(--spacing-20)",
        24: "var(--spacing-24)",
        28: "var(--spacing-28)",
        32: "var(--spacing-32)",
        36: "var(--spacing-36)",
        40: "var(--spacing-40)",
        44: "var(--spacing-44)",
        48: "var(--spacing-48)",
        52: "var(--spacing-52)",
        56: "var(--spacing-56)",
        60: "var(--spacing-60)",
        64: "var(--spacing-64)",
        72: "var(--spacing-72)",
        80: "var(--spacing-80)",
        96: "var(--spacing-96)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      borderWidth: {
        none: "var(--border-none)",
        thin: "var(--border-thin)",
        DEFAULT: "var(--border-normal)",
        thick: "var(--border-thick)",
        thicker: "var(--border-thicker)",
        thickest: "var(--border-thickest)",
      },
      boxShadow: {
        none: "var(--shadow-none)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-md)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        inner: "var(--shadow-inner)",
        focus: "var(--shadow-focus)",
        glow: "var(--shadow-glow)",
        "glow-strong": "var(--shadow-glow-strong)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
        slowest: "var(--duration-slowest)",
      },
      transitionTimingFunction: {
        linear: "var(--ease-linear)",
        in: "var(--ease-in)",
        out: "var(--ease-out)",
        "in-out": "var(--ease-in-out)",
        bounce: "var(--ease-bounce)",
      },
      zIndex: {
        hide: "var(--z-hide)",
        auto: "var(--z-auto)",
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
        toast: "var(--z-toast)",
        overlay: "var(--z-overlay)",
        "skip-link": "var(--z-skip-link)",
      },
      screens: {
        sm: "var(--breakpoint-sm)",
        md: "var(--breakpoint-md)",
        lg: "var(--breakpoint-lg)",
        xl: "var(--breakpoint-xl)",
        "2xl": "var(--breakpoint-2xl)",
      },
      maxWidth: {
        "container-sm": "var(--container-sm)",
        "container-md": "var(--container-md)",
        "container-lg": "var(--container-lg)",
        "container-xl": "var(--container-xl)",
        "container-2xl": "var(--container-2xl)",
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-primary-hover": "var(--gradient-primary-hover)",
        "gradient-hero": "var(--gradient-hero)",
        "gradient-hero-alt": "var(--gradient-hero-alt)",
        "gradient-card": "var(--gradient-card)",
        "gradient-accent": "var(--gradient-accent)",
        "gradient-mesh": "var(--gradient-mesh)",
      },
      animation: {
        "fade-in": "fadeIn var(--duration-normal) var(--ease-out)",
        "slide-up": "slideUp var(--duration-slow) var(--ease-out)",
        "slide-down": "slideDown var(--duration-slow) var(--ease-out)",
        "scale-in": "scaleIn var(--duration-fast) var(--ease-out)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;